openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contact book app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-7-s2kq.onrender.com
paths:
  /contacts:
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: '../swagger/components/schemas/Contact.yaml'
  responses:
    '401':
      $ref: '../swagger/components/responses/401.yaml'
    '404':
      $ref: '../swagger/components/responses/404.yaml'
    '500':
      $ref: '../swagger/components/responses/500.yaml'
